### ISSUE TITLE
Unable to use with React 15.1.0

### ISSUE THREAD

**Issue by jameseggers** [bvaughn/react-virtualized-select#13]
Hey,

I'm unable to make this work with React 15.1.0, the error I'm receiving is:

```
bexie_uni@1.0.0 /Users/jameseggers/Projects/bexie_uni
├── UNMET PEER DEPENDENCY react-addons-shallow-compare@^0.14.0 || ^15.0.0
└─┬ react-virtualized-select@1.0.0 
  ├── UNMET PEER DEPENDENCY react-addons-shallow-compare@^0.14.0 || ^15.0.0
  └─┬ react-virtualized@7.6.0 
    └─┬ raf@3.2.0 
      └── performance-now@0.2.0

npm WARN react-virtualized-select@1.0.0 requires a peer of react-addons-shallow-compare@^0.14.0 || ^15.0.0 but none was installed.
npm WARN react-virtualized@7.6.0 requires a peer of react-addons-shallow-compare@^0.14.0 || ^15.0.0 but none was installed.
```

Any ideas?

**Comment by 2slow** [comment]
Had the same issue on react 15.1, and all I had do was running npm install react-addons-shallow-compare --save to fix the problem

**Comment by jameseggers** [comment]
@2slow that worked, I have it installed, I'm able to load options into the select element but I'm seeing some weird behaviour - the options kinda jump around a little and if you scroll down too far they all disappear. Is it working as expected for you?

**Comment by 2slow** [comment]
Did you require the CSS file or react-select as mentioned in [https://github.com/bvaughn/react-virtualized-select/issues/6](https://github.com/bvaughn/react-virtualized-select/issues/6) It's not in the read.me file yet but did the trick for me.

**Comment by jameseggers** [comment]
Ah, that's probably it. Will close when I try it later, thanks!

**Comment by bvaughn** [comment]
Hey guys! I'm _extremely_ sorry for not seeing this issue earlier. Something got messed up somehow with my watch settings and I haven't been receiving any notifications for this project.

The issue of seeing blank rows after you scroll past the first "page" of rows is indeed because the react-virtualized CSS styles have not been included. The README example has been updated to show this step. That should resolve things for you! Sorry again! :(
