### ISSUE TITLE
Styling the selected value

### ISSUE THREAD

**Issue by anisbi** [bvaughn/react-virtualized-select#140]
Hey,

Using `optionRenderer` I was able to style the components of the Selection List.

I would like to be able to style the selected option (collapsed) in the form.

In this gif you can see how the Courier logos appear in the drop down, but once the value is selected the styling isn't applied to the selected component:
![courierlogo](https://user-images.githubusercontent.com/17564575/55884641-14558a00-5bb1-11e9-845f-497c92397259.gif)

Is there an official way to achieve this?

Thanks.

**Comment by bvaughn** [comment]
The collapsed UI is rendered by react-select, not this library. This library just renders the menu (drop down) portion and otherwise passes params through to react-select:
https://github.com/bvaughn/react-virtualized-select/blob/aa47a7f43bb7574acbd47ab1483e737d66979b6a/source/VirtualizedSelect/VirtualizedSelect.js#L50-L61

I'd suggest checking out the docs for react-select on how to style it 😄
