### ISSUE TITLE
Filtering Performance with Large Lists (2000+)

### ISSUE THREAD

**Issue by turnerniles** [bvaughn/react-virtualized-select#20]
After playing around with the virtualized select (without filtering) it works performantly even with 1 million records. However when filtering based on user input it comes to a crawl around 2000-3000 items. Would you have any suggestion as to how to make the filtering more performant?

Looking at the react-select repo issues, a few people are having the same problem. 
https://github.com/JedWatson/react-select/issues/807
https://github.com/JedWatson/react-select/issues/739

But I don't believe react-virtualized-select solves the issue.

**Comment by bvaughn** [comment]
I _think_ this problem comes down to how filtering is done within `react-select` (aka [synchronously, in the UI thread](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L826-L864). For large lists, this is going to hurt FPS.

I've created some JS search libs (eg [`js-worker-search`](https://github.com/bvaughn/js-worker-search), [`redux-search`](https://github.com/treasure-data/redux-search)) that do this type of filtering in web-workers, using data structures optimized for fast look-up. The response time for filtering drop-down lists using them is _very fast_.

Perhaps that would be interest in trying to integrate one within `react-select`?

I'm going to close this issue b'c there's nothing `react-virtualized-select` can do to speed up filtering performance in `react-select`. I will add a comment like the one I wrote above to the 2 issues you linked and we'll see what Jed thinks when he gets a chance to weigh-in. :)

**Comment by turnerniles** [comment]
@bvaughn I agree with the above; however, react-select cannot performantly render 3000+ items without using react-virtualized-select. Would react-select want to implement the faster js search libs if they don't support large lists? React-select does allow advanced filtering options. Is it something that could be built in react-virtualized-select on top of react-select?

**Comment by bvaughn** [comment]
Definitely! `react-virtualized-select` would still have a place in speeding things up too. :)

I like using high-order components for this sort of functionality because (a) it doesn't bloat or add complexity to the underlying library (`react-select`) and (b) it lets users opt-in if they need the functionality. Lots of users just want a simple, styled drop-down menu and `react-select` works fine for that.

I was tentatively thinking of creating another light-weight lib that connects `js-worker-search` and `react-select` so people wanting to filter large lists of options could use _that_ library as their `filterOptions` property. So basically something like this...

```js
import React, { Component } from 'react'
import VirtualizedSelect from 'react-virtualized-select'
import fastFilterOptions from 'react-select-fast-filter-options'

function MyComponent () {
  return (
    <VirtualizedSelect
      {...props}
      filterOptions={fastFilterOptions}
    />
  )
}
```

**Comment by NathanBWaters** [comment]
@bvaughn just saying I would totally use a higher order component that combines `react-virtualized-select` and `js-worker-search` because currently `createFilterOptions from` 'react-select-fast-filter-options' makes the main thread hang.

**Comment by bvaughn** [comment]
`js-worker-search` is fast because it offloads work to a service worker. But since `postMessage ` is async, then everything- including searches- is async. `react-select` doesn't support an async `filterOptions` prop unfortunately so...dead end.

If `react-select` supported an async `filterOptions` it would be an easy thing to connect the 2.

**Comment by NathanBWaters** [comment]
Thanks for the response!  If my team is down for the time it takes, it sounds like a PR on my part is in order.

**Comment by bvaughn** [comment]
If you go this route, keep me posted and feel free to CC me on the `react-select` end. I help maintain that project, although I rarely have the time to any more. I'd try to make an exception for something like this though. 😄
