### ISSUE TITLE
missing dependencies - react-addons-shallow-compare

### ISSUE THREAD

**Issue by eyala-stratoscale** [bvaughn/react-virtualized-select#24]
react-addons-shallow-compare is currently in devDependencies , should be in dependencies

**Comment by bvaughn** [comment]
`react-addons-shallow-compare` (like the other React modules) actually belong in `peerDependencies` (which is [where it is](https://github.com/bvaughn/react-virtualized-select/blob/master/package.json#L123-L126)). This is required for React 0.14 support.

It only happens to be in `devDependencies` as well because of the demo site I build. 😄

**Comment by eyala-stratoscale** [comment]
Getting Many 
ERROR in ./~/react-virtualized/dist/commonjs/ArrowKeyStepper/ArrowKeyStepper.js
Module not found: Error: Cannot resolve module 'react-addons-shallow-compare' in /home/eyala/work/mui2.0/js/client/node_modules/react-virtualized/dist/commonjs/ArrowKeyStepper
 @ ./~/react-virtualized/dist/commonjs/ArrowKeyStepper/ArrowKeyStepper.js 13:33-72

errors after adding react-virtualized-select package and trying to use it.
Maybe an issue with react-virtualized

**Comment by bvaughn** [comment]
You'll need to install `react-addons-shallow-compare` but I can't mark it as a `dependency` without breaking React 0.14 support. Npm should show you a warning about this when you install the lib. I've mentioned it in the docs [here](https://github.com/bvaughn/react-virtualized#dependencies).

The fix should be simple for you:
```sh
npm i --save react-addons-shallow-compare
```

😄

**Comment by eyala-stratoscale** [comment]
yes, easy fix ... .nevermind then... thanks
