### ISSUE TITLE
Select all filtered

### ISSUE THREAD

**Issue by r1g0** [bvaughn/react-virtualized-select#25]
Hello, I've been using this select and so far it's great but I found the need to use a 'select all shown' option.

I am planning to do it now, have you thought about it? do you have any recommendations?
 
![screen shot 2016-10-06 at 3 43 27 pm](https://cloud.githubusercontent.com/assets/1535107/19172214/ddf361ee-8bdd-11e6-8f6c-040169590f70.png)

**Comment by bvaughn** [comment]
Hm. Interesting.

Initially, I don't think this feature belongs inside of `react-virtualized-select`. I'm not even sure it belongs inside of the drop-down portion of the select at all. Seems like maybe it would be better shown in the top section you can type within. Putting it within the drop-down list seems kind of like a confusing UX because (a) not all things in the list are the same type of thing now and (b) as you scroll down, that option would be hidden.

**Comment by r1g0** [comment]
Ok, good point.  What about this?

![screen shot 2016-10-06 at 4 40 49 pm](https://cloud.githubusercontent.com/assets/1535107/19173259/b5e0527e-8be3-11e6-8696-84172c9297ac.png)

I was thinking of perhaps changing the word "select" for an icon, or leaving it like this.

**Comment by bvaughn** [comment]
In my opinion, this is a better UX. 👍

You should be able to implement this within react-select by overriding the default `inputRenderer`. react-virtualized-select only controls what is rendered within the drop-down window.

**Comment by bvaughn** [comment]
If you do implement this, it might be nice to release it as its own add-on component (similar to this library or [react-select-fast-filter-options](https://github.com/bvaughn/react-select-fast-filter-options).

**Comment by bvaughn** [comment]
I'm going to close this issue for now as I don't think it's react-virtualized-select specific. This library [only concerns itself with the `menuRenderer`](https://github.com/bvaughn/react-virtualized-select/blob/master/source/VirtualizedSelect/VirtualizedSelect.js#L36-L46). All other properties are passed through to react-select.

**Comment by r1g0** [comment]
Ok, will do. Thanks for the help.

**Comment by bvaughn** [comment]
No problem~ 😄
