### ISSUE TITLE
Add support for "infinite" async options

### ISSUE THREAD

**Issue by leftmostcat** [bvaughn/react-virtualized-select#26]
Currently, there's no provision in the use of `loadOptions` to do paged queries. A property for `loadPagedOptions` or similar whose signature included a row count would allow for use of the component in cases where there may be a large number of results which it may be impractical or impossible to narrow by additional search terms.

**Comment by bvaughn** [comment]
Hey @leftmostcat,

This request would require support from [react-select](https://github.com/JedWatson/react-select/) as [`loadOptions`](https://github.com/JedWatson/react-select#async-options-with-promises) belongs to it. react-virtualized-select (this project) just deals with showing large option lists once loaded.

The only touch-points here is that react-virtualized `rowCount` is determined by the number of options.

Looks like some related efforts are in progress for react-select:
* [PR 1237](https://github.com/JedWatson/react-select/pull/1237): add async pagination
* [issue 568](https://github.com/JedWatson/react-select/issues/568#issuecomment-153785740): Version 1.0 roadmap
* [issue 644](https://github.com/JedWatson/react-select/issues/644): Load on scroll/pagination

I'm going to close _this_ issue since I think this will likely be entirely handled within react-select. If it turns out that a change is required in react-virtualized-select as well, I'll re-open it. 😄
