### ISSUE TITLE
Unable to select text in the input box

### ISSUE THREAD

**Issue by freeranger** [bvaughn/react-virtualized-select#31]
I want to be able to select all the entered text by default when the input gets the focus (and be able to change which bit is selected once I have the focus - left-mouse drag) but neither seem to work.
I have an onFocus method:
```jqavascript
onFocus={(event) => {
                    console.log('Focus');
                      var target = event.target;
                      setTimeout(function() {
                          target.select();
                       }, 0);
                    }}
```
but it doesn't do the job - it is called (I get the log message) but the text does not get selected, and nor can I use the mouse (or keyboard) to select the text in the box.
Use of the timeout is because various people report this doesn't work in general with Chrome without a tiny delay but I have tried without the timeout element and still no joy :/

**Comment by bvaughn** [comment]
Pretty sure this issue should be filed against [react-select](https://github.com/JedWatson/react-select/). This library (react-virtualized-select) is just a convenience wrapper around that one. It renders the drop-down area using react-virtualized. The text input you're referring to is rendered entirely by react-select.

Going to close this issue here for now. I suggest you re-open it [here](https://github.com/JedWatson/react-select/issues/new).

Please let me know if I misunderstood things. 😄
