### ISSUE TITLE
Createable Options On Click Does Not Add to List 

### ISSUE THREAD

**Issue by turnerniles** [bvaughn/react-virtualized-select#33]
Looking at http://bvaughn.github.io/react-virtualized-select/

Creating your own options works when you type in a custom options and hit the 'enter' key. However, if you type in a custom option and then click on the custom option it will not add it to the list. 

Adding on a custom option on click does work on the non-virtulized react-select. http://jedwatson.github.io/react-select/

**Comment by bvaughn** [comment]
My demo was built prior to the most recent release candidate of react-select. Are you seeing this bug yourself, running the newest versions of both?

**Comment by turnerniles** [comment]
Yes, I am running react-select version 1.0.0-rc.2 and react-virtualized-select v.2.1.0. The react-select demo is running an older version on their demo site but I checked react-select without virtualized select and it works.

**Comment by turnerniles** [comment]
Logging what it's trying to add when try adding a custom option "test" and I click:
["Create option "test""]
Logging what it's trying to add when try adding a custom option "test" and I hit enter:
["test"]

**Comment by bvaughn** [comment]
Looks like this is actually due to a bug in react-select `Creatable`. I've added a workaround in react-virtualized-select (released as version 2.1.1) and I'll make sure the fix gets added upstream in react-select. Thanks for the report.

**Comment by turnerniles** [comment]
Thank you bvaughn

**Comment by michalvankodev** [comment]
I've just noticed.. When I use `promptTextCreator`. I have a really bad behavior when using `enter`. It creates a new option twice. First time without `promtText` but it gets immediately replaced with new option which will include whole output of `promptTextCreator`. It only happens when I submit the option with `enter` key.

**Comment by michalvankodev** [comment]
Ok, You can ignore my comment. I just found out that we've used wrong function signature for `shouldKeyDownEventCreateNewOption`. Which will cause always return false and then the event propagated to normal `this.select.selectValue(this._focusedOption);` instead of `this.createNewOption()` in Creatable.

**Comment by bvaughn** [comment]
Thanks for the update.

**Comment by alpesh1988** [comment]
Hey @bvaughn , I am facing this issue in react-virtualized-select library latest version.

I've posted post on stackoverflow https://stackoverflow.com/questions/47881613/creatable-props-not-working-in-react-virtualized-select-component

Can you pls take a look at it and help me if possible ?

Thanks,
Alpesh
