### ISSUE TITLE
Using loadOptions instead of explicitly passing a list of options

### ISSUE THREAD

**Issue by rgfoley** [bvaughn/react-virtualized-select#4]
Hi, first off I'd like to say I really like the enhancements you've made to react-select. One issue I've run into (and maybe it's just painfully obvious and I don't see it) is that there is no way to use the loadOptions prop which is available against the Select.Async component.

The biggest use-case for using virtualized option scrolling is when there is a large list of options, and I would imagine that such a list would likely be loaded asynchronously.

If not with generic support against the VirtalizedSelect component, then exposing the functionality through something like VirtualizedSelect.Async or something to that effect would be greatly appreciated.

Again, if such functionality is possible with the existing interface, I'd love to know.

**Comment by bvaughn** [comment]
I'm very sorry for ignoring this issue for so long. My Github "watch" setting was somehow deactivated without my realizing it and I didn't receive notifications for this project.

I'm not familiar with the Select.Async use case. I'm a bit behind because of the watch issue so I'm not sure how soon I can get to this- but I'll try to take a look at some point by the weekend and see if it's something I can support in react-virtualized-select as well.

In the meanwhile, I'd welcome any input or suggestions you have. I promise, I'll actually be "watching" this time. :)

**Comment by bvaughn** [comment]
Getting a chance to look at this now. Async options are now supported via a new `async` property.

Check out a demo [here](https://bvaughn.github.io/react-virtualized-select/) and the source code [here](https://github.com/bvaughn/react-virtualized-select/blob/master/source/VirtualizedSelect/VirtualizedSelect.example.js#L152-L182).

**Comment by nafg** [comment]
If you're loading data from ajax, your bottleneck is not just overloading the DOM, it's also loading more items than you need. How do you load only one page of data at a time?
