### ISSUE TITLE
optionRenderer overrides react-select optionsRenderer

### ISSUE THREAD

**Issue by ambewas** [bvaughn/react-virtualized-select#43]
The optionRenderer prop that is defined in react-virtualized-select should actually be named menuRenderer --  which is what is the corresponding prop is in react-select. 

Right now, if you want to swap out react-select with react-virtualized-select and had already defined a custom optionRenderer in react-select, it's incompatible. 

OptionRenderer in react-select only receives an option `{value: 1, label: 'one'}` as argument. In react-virtualized-select you get all the options you would expect in menuRenderer.

**Comment by bvaughn** [comment]
> The optionRenderer prop that is defined in react-virtualized-select should actually be named menuRenderer -- which is what is the corresponding prop is in react-select.

I'm curious why you would think this? The 2 props are concerned with different things.

I introduced the `menuRenderer` prop to react-select as a way for react-virtualized to be plugged into drop-down. That prop renders the entire set of select options. react-virtualized-select plugs react-virtualized in with this prop in order to only render the visible options.

The `optionRenderer` prop in react-virtualized-select renders a _single option_ (within the larger menu rendered by `menuRenderer`). Its name mirrors the prop in react-select although they are not guaranteed to receive the exact same parameters.

**Comment by ambewas** [comment]
They are, which is why I was confused wen I got different arguments in the same optionRenderer when I swapped out react-select with react-virtualized. In the latter I got all the options available in the menuRenderer in react-select.

Thanks for the reply though!

**Comment by bvaughn** [comment]
Ah, I understand. 😄 No problem.
