### ISSUE TITLE
Cant we add new stuff to options ?

### ISSUE THREAD

**Issue by vivinRajagopalan** [bvaughn/react-virtualized-select#5]
Hi,
I am new to react and i was using react select . I have a question. Cant we add to options if we dont find in the list of objects. For Eg. If am searching a city which is not there in the list, cant i add the the city to the list instead of showing no contents found ?

Please let me know

Thanks,
Vivin

**Comment by bvaughn** [comment]
Hi @vivinRajagopalan, I'm very sorry for ignoring this issue for so long. My Github "watch" setting was somehow deactivated without my realizing it and I didn't receive notifications for this project.

This sounds like something that your application logic should manage rather than react-virtualized-select. This project (and react-virtualized underneath) doesn't create any data. It just displays it. If the user enters a search string that doesn't match any results- you could insert a result and then it would appear in the filtered list. react-select has support for this.

I'm going to close this as a no-op for react-virtualized-select b'c I think the solution belongs in your application and/or react-select. But let me know if my response is confusing. :)
