### ISSUE TITLE
Typings error with Typescript 2.4.1

### ISSUE THREAD

**Issue by borNfreee** [bvaughn/react-virtualized-select#66]
Not sure this is a right repository to post this issue, but there is an error in Typings when Typescript 2.4.1 is used:

```js
ERROR in [at-loader] ./node_modules/@types/react-virtualized-select/index.d.ts:25:18
    TS2430: Interface 'VirtualizedSelectProps' incorrectly extends interface 'ReactSelectProps'.
  Types of property 'optionRenderer' are incompatible.
    Type '(options: VirtualizedOptionRenderOptions<any>) => Element' is not assignable to type '(option: Option) => Element'.
      Types of parameters 'options' and 'option' are incompatible.
        Type 'Option' is not assignable to type 'VirtualizedOptionRenderOptions<any>'.
          Property 'focusedOption' is missing in type 'Option'.
```

Versions:

`@types/react-virtualized-select-3.0.1`
`react-virtualized-select-3.0.1`
`react-virtualized-9.8.0`

```bash
node_modules/.bin/tsc --version
Version 2.4.1
```

**Comment by bvaughn** [comment]
I think you should file this against [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) since [`VirtualizedSelectProps `](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-virtualized-select/index.d.ts) comes from there. 😄  I don't have anything to do with that effort.
