### ISSUE TITLE
scrolling, grid data gets our of sync on large data size

### ISSUE THREAD

**Issue by mikesmithut** [bvaughn/react-virtualized-select#7]
As I scroll down, after about 20, I start to see a large white space at the end of the list.  I can see items added, but everything scrolls up until the whole selection list is just white and now entries seen,  As I scroll back up the list I can see items come back into view and the list items on the end are being removed.  I am not sure if its a CSS issue between the Grid object the scrolling area, or what.

**Comment by jeroenbourgois** [comment]
I am experiencing exact the same issue :(

**Comment by bencrinkle** [comment]
same here on a dataset of about 2500, get the first 20 or so and then blank.

**Comment by bvaughn** [comment]
Hey guys! I'm _extremely_ sorry for not seeing this issue earlier. Something got messed up somehow with my watch settings and I haven't been receiving any notifications for this project.

This issue is because you're not including react-virtualized CSS file. Which is in turn because my README example didn't show it. That has since been corrected. Very sorry!

**Comment by Stenerson** [comment]
@bvaughn I just started playing with this today (@ v1.3) and I'm experiencing this. 

I've validated that I'm loading the styles.css file (there's a noticeable style difference when I remove the import to styles) not sure what else to check. Any ideas? Thanks!
