### ISSUE TITLE
Option's text overlaps with Creatable Option

### ISSUE THREAD

**Issue by CalvinChhour** [bvaughn/react-virtualized-select#84]
I have a `VirtualizedSelect` that takes up approximately 180 pixels width wise. When the options within line wrap or are too long, the text can be seen overlapping each other like so:
![React-Virtualized-Select Example](https://i.imgur.com/MfBPbw0.png)
Whereas when I use `react-select` I get properly sized option boxes:
![React-Select Example](https://i.imgur.com/L8oWTnS.png)

I know that `optionHeight` can be set as a property and is defaulted to 35px, so perhaps this is intended. I've tried figuring out an auto-size solution or trying to dynamically set the height with `optionHeight` but haven't been able to get it to work as perfectly as it does in react-select. 

Easy way to reproduce this is: 
1. Go to [the project sample](https://bvaughn.github.io/react-virtualized-select/) 
2. Make window as small (width wise) as you can. (This makes the option box smaller and imitates the case where you have a large object to the right of the option box)
3. Add inputs that might be too long or line wrap into the Creatable Options field.. like so: 
![From sample](https://i.imgur.com/lPGpP77.png)

I am currently on react-virtualized-select version 2.4.0 but I still notice the issue on the latest release.

**Comment by bvaughn** [comment]
This is working as designed.

`react-virtualized-select` is built on top of the [`react-virtualized`](https://github.com/bvaughn/react-virtualized) library in order to perform faster with large result sets. In order for this library to work, it relies on absolute positions- and so it doesn't use normal block or flexbox layout like `react-select` does.

This is why the [docs](https://github.com/bvaughn/react-virtualized-select#react-virtualized-select-props) say `optionHeight` is a required prop.

`react-virtualized` supports runtime size calculation with `CellMeasurer` but that's not really something I plan to add to this library. I'd recommend forking this library instead (it's small) if you want to integrate that component. 😄

**Comment by CalvinChhour** [comment]
Got it, thanks for the prompt response! :smile:
