### ISSUE TITLE
Auto select value from option list, when there is only one value in list

### ISSUE THREAD

**Issue by brajeshchandra2002** [bvaughn/react-virtualized-select#95]
We are facing a problem to auto populate a option when there is only one value in list.

Requirement: in dropdown, a value should be pre-populated or rendered on page load. 
Current behavior: on clicking on dropdown  options are clickable and rendered on dropdown.

We are tried to find a suitable configuration in component, but could not found.

Please anyone help us to get this resolved.

Thanks in advance.

**Comment by bvaughn** [comment]
Hello! 😄 

For this type of question, I suggest using a site like Stack Overflow. Issues are reserved for bug reports and feature-requests.

I also suggest linking to a Code Sandbox demo (or similar) that shows _what you've tried_ to give people an easier way to answer your question with specifics (which will be helpful to you).

This helps keep the project somewhat more maintainable for me _and_ hopefully gets you an answer faster (since more people check those places than monitor GitHub issues). 😄
