### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by oonsamyi** [bvaughn/react-virtualized-select#99]
`react-virtualized-select` radically dependent on [`react-select`](https://github.com/JedWatson/react-select) library version [1.0.0-rc.2](https://github.com/bvaughn/react-virtualized-select/blob/master/package.json#L124).
But the latest version `react-select` is [1.2.1](https://github.com/JedWatson/react-select/releases/tag/v1.2.1). And already exists [alpha](https://github.com/JedWatson/react-select/releases/tag/v2.0.0-alpha.1) version!
Same story with `react-virtualized`: the latest version is [9.17.3](https://github.com/bvaughn/react-virtualized/releases/tag/9.17.3), but `react-virtualized-select` uses [9.0.0](https://github.com/bvaughn/react-virtualized-select/blob/master/package.json#L125) version.
Why there is no update of dependencies?
Can I assume that `react-virtualized-select` is abandoned?

**Comment by bvaughn** [comment]
> Can I assume that react-virtualized-select is abandoned?

The last commit to this project was 4 days ago. The last release to NPM was 6 days ago. My response time for this GitHub issue is ~3 hours (it's 7am here). The project is certainly not abandoned.

Your questions about dependency ranges, I think, suggest a small misunderstanding of how dependencies work.

For example, react-select. Your are welcome to install the latest 1.2.1 release. If will work with this project. This package simply specifies any version after ^.0.0-rc.2 (because it also works with the old versions too). I could update the dependency, but why should I? It's unnecessary and would technically be a backwards breaking change for anyone using an older version of react-select for some reason.

I don't yet have the alpha included because it's an alpha and there may be compatibility problems. At some point, I'm sure the newer version will be added as well.

I don't understand what point that  issue is intended to make? It sounds like complaining, but it's early here and maybe I'm just reading it wrong. 🙂

**Comment by turnerniles** [comment]
@oonsamyi When you ```yarn``` or ```npm install```, it will install the latest version of react-select and react-virtualized up to but not including the next major version because of the [caret](https://stackoverflow.com/questions/22137778/what-does-mean-in-package-json-versioning) put next to those dependencies in the package.json 
```
"react-select": "^1.0.0-rc.2",
"react-virtualized": "^9.0.0".
```

See the versions actually installed in yarn log below.

```
yarn add react-virtualized-select
yarn add v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-virtualized-select > react-select@1.2.1" has unmet peer dependency "react@^0.14.9 || ^15.3.0 || ^16.0.0-rc || ^16.0".
warning "react-virtualized-select > react-select@1.2.1" has unmet peer dependency "react-dom@^0.14.9 || ^15.3.0 || ^16.0.0-rc || ^16.0".
warning "react-virtualized-select > react-virtualized@9.18.0" has unmet peer dependency "react@^15.3.0 || ^16.0.0-alpha".
warning "react-virtualized-select > react-virtualized@9.18.0" has unmet peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha".
warning "react-virtualized-select > react-select > react-input-autosize@2.2.1" has unmet peer dependency "react@^0.14.9 || ^15.3.0 || ^16.0.0-rc || ^16.0".
warning " > react-virtualized-select@3.1.1" has unmet peer dependency "react@^15.3.0 || ^16.0.0-alpha".
warning " > react-virtualized-select@3.1.1" has unmet peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 17 new dependencies.
├─ asap@2.0.6
├─ classnames@2.2.5
├─ dom-helpers@3.3.1
├─ encoding@0.1.12
├─ fbjs@0.8.16
├─ is-stream@1.1.0
├─ isomorphic-fetch@2.2.1
├─ node-fetch@1.7.3
├─ promise@7.3.1
├─ prop-types@15.6.0
├─ react-input-autosize@2.2.1
├─ react-select@1.2.1
├─ react-virtualized-select@3.1.1
├─ react-virtualized@9.18.0
├─ setimmediate@1.0.5
├─ ua-parser-js@0.7.17
└─ whatwg-fetch@2.0.3
✨  Done in 3.97s.
```

**Comment by oonsamyi** [comment]
@bvaughn Thanks for the quick and full answer! I'm sorry, it was my omission. You are right, I set myself a new version using `npm update react-virtualized-select`.
@turnerniles Thank you for the clarification!
